syntax = "proto3";

package product;

option go_package = "github.com/poshagator/content-service/pkg/proto/product/gen;product";

service ProductService {
  rpc UpsertProduct(UpsertProductRequest) returns (UpsertProductResponse);
  rpc BatchUpsertProducts(BatchUpsertProductsRequest) returns (BatchUpsertProductsResponse);

  rpc UpsertCategory(UpsertCategoryRequest) returns (UpsertCategoryResponse);
  rpc BatchUpsertCategories(BatchUpsertCategoriesRequest) returns (BatchUpsertCategoriesResponse);

  rpc UpsertFuel(UpsertFuelRequest) returns (UpsertFuelResponse);
  rpc BatchUpsertFuels(BatchUpsertFuelsRequest) returns (BatchUpsertFuelsResponse);

  rpc UpsertExternalAction(UpsertExternalActionRequest) returns (UpsertExternalActionResponse);
  rpc BatchUpsertExternalActions(BatchUpsertExternalActionsRequest) returns (BatchUpsertExternalActionsResponse);
}

// ======================= Products =======================

message ProductInput {
  string external_id = 1;
  string title = 2;
  string body = 3;
  double base_price = 4;
  string currency = 5;
  string weight = 6;
  string volume = 7;
  optional bool status = 8;
  repeated string media_urls = 9;
}

message UpsertProductRequest {
  string filial_id = 1;
  string source = 2;
  ProductInput product = 3;

  optional string category_id = 4;
  optional string category_external_id = 5;
  optional string category_name = 6;
}

message UpsertProductResponse {
  string product_id = 1;
  bool created = 2;
}

message BatchUpsertProductsRequest {
  repeated UpsertProductRequest products = 1;
}

message BatchUpsertProductsResponse {
  repeated UpsertProductResponse products = 1;
}

// ======================= Categories =======================

message CategoryInput {
  string external_id = 1;
  string name = 2;
  optional string photo_url = 3;
  optional string type = 4;
}

message UpsertCategoryRequest {
  string filial_id = 1;
  string source = 2;
  CategoryInput category = 3;
}

message UpsertCategoryResponse {
  string category_id = 1;
  bool created = 2;
}

message BatchUpsertCategoriesRequest {
  repeated UpsertCategoryRequest categories = 1;
}

message BatchUpsertCategoriesResponse {
  repeated UpsertCategoryResponse categories = 1;
}

// ======================= Fuels =======================

message FuelInput {
  string name = 1;
  double price = 2;
}

message UpsertFuelRequest {
  string filial_id = 1;
  FuelInput fuel = 2;
}

message UpsertFuelResponse {
  string fuel_id = 1;
  bool created = 2;
}

message BatchUpsertFuelsRequest {
  repeated UpsertFuelRequest fuels = 1;
}

message BatchUpsertFuelsResponse {
  repeated UpsertFuelResponse fuels = 1;
}

// ======================= External Actions =======================

message ExternalActionInput {
  string title = 1;
  string url = 2;
}

message UpsertExternalActionRequest {
  string filial_id = 1;
  ExternalActionInput action = 2;
}

message UpsertExternalActionResponse {
  string action_id = 1;
  bool created = 2;
}

message BatchUpsertExternalActionsRequest {
  repeated UpsertExternalActionRequest actions = 1;
}

message BatchUpsertExternalActionsResponse {
  repeated UpsertExternalActionResponse actions = 1;
}
