syntax = "proto3";
package order;
option go_package = "github.com/Poshagator/order-service/pkg/proto/gen/go/orderpb";

import "google/protobuf/timestamp.proto";

// ───────────────────────── Input ─────────────────────────
message OrderItemInput {
  string product_id     = 1;
  int32  qty            = 2;
  string modifiers_json = 3;
}

message DeliveryInfo {
  string address_id     = 1;
  google.protobuf.Timestamp delivery_time = 2;
}

message TakeawayInfo {
  google.protobuf.Timestamp pickup_time = 1;
}

message TableInfo {
  string table_number = 1;
}

message CreateOrderRequest {
  string filial_id  = 1;
  string user_id    = 2;
  string type_code  = 3;                       // delivery | takeaway | table
  repeated OrderItemInput items = 4;
  string comment    = 5;

  oneof details {
    DeliveryInfo delivery = 6;
    TakeawayInfo takeaway = 7;
    TableInfo    table    = 8;
  }
}

// ───────────────────────── Output ────────────────────────
message Order {
  string id          = 1;
  string filial_id   = 2;
  string user_id     = 3;
  string type_code   = 4;
  string status_code = 5;
  double total_price = 6;
  string currency    = 7;
  google.protobuf.Timestamp created_at = 20;
}

message CreateOrderResponse {
  oneof result {
    Order order = 1;
    Error error = 2;
  }
}

message Error {
  string message = 1;
  int32  code    = 2;
}

service OrderService {
  rpc CreateOrder (CreateOrderRequest) returns (CreateOrderResponse);
}
