BEGIN;

DROP TABLE IF EXISTS timetable_exception CASCADE;
DROP TABLE IF EXISTS timetable_entry CASCADE;
DROP TABLE IF EXISTS edu_group CASCADE;
DROP TABLE IF EXISTS academic_term CASCADE;
DROP TABLE IF EXISTS staff CASCADE;
DROP TABLE IF EXISTS person CASCADE;
DROP TABLE IF EXISTS room CASCADE;
DROP TABLE IF EXISTS edu_subject CASCADE;

DROP TABLE IF EXISTS product CASCADE;
DROP TABLE IF EXISTS product_category CASCADE;

DROP TABLE IF EXISTS media_file CASCADE;
DROP TABLE IF EXISTS filial CASCADE;

COMMIT;
